### PR TITLE
updates to flowsa metadata

### PR DESCRIPTION
**Pull request by catherinebirney**
- option to specify git version/hash when returning an FBA
- new fxn `compare_FBA_results()` to compare the results of two FBA dataframes
- new github action to compare an FBA method to an FBA parquet on Data Commons
- updates to FBS metadata - output json captures the metadata for all FBAs identified in an FBS yaml for all recrusive/sequential datasets
- drop FBS in source_catalog. Update all calls of Employment FBS in method yamls to include data_format definition
- updates to FBA publication and download dates

### CODE REVIEW

**Comment by catherinebirney** [comment]
@bl-young Once the checks complete I'd like to pull this PR into master to check the new compare FBA github action is working correctly

**Comment by bl-young** [comment]
You can also commit `.github/workflows/compare_single_FBA.yml` by itself directly to master and then test on this branch without pulling everything else in first

**Comment by catherinebirney** [comment]
> You can also commit `.github/workflows/compare_single_FBA.yml` by itself directly to master and then test on this branch without pulling everything else in first

That is a better idea, I will do that, thanks!

**Comment by catherinebirney** [comment]
@bl-young The new github action works. I am done with changes on this branch, so this PR is ready to be pulled in

**Comment by catherinebirney** [comment]
I locally tested on FBAs that have changed - Census_PEP_Poplulation changed between v1.3.0 and v2.0.0 but there won't be any differences in the FBAs flowsa creates right now vs what is on data commons, so you would need to download those files

**Review by bl-young — COMMENTED** [review]
is `source_publication_date` meant to appear in the FBA metadata?

**Comment by catherinebirney** [comment]
yes, thanks - I added the source pub date to FBA metadata json. I'll pull this in when the checks are done

**Pull request merged**
