### PR TITLE
in FBS method yaml split primary source FBS into activity sets for attribution

### PR DESCRIPTION
**Pull request by catherinebirney**
- in food waste national 2018 m2, want to load an FBS as a primary source, split into activity sets and use attribution sources to further attribute

### CODE REVIEW

**Comment by matthewlchambers** [comment]
Assuming my generalized disaggregation code works, it will cover this situation as well, since I'm implementing it for the parent `_FlowBy` class.

**Comment by catherinebirney** [comment]
Thanks @matthewlchambers - I will hold off on any additional changes on this branch

**Comment by catherinebirney** [comment]
closing in favor of the work in attribution-disaggregation branch

**Comment by catherinebirney** [comment]
closing - pulled this data into proportional_attribution

**Pull request closed without merging**
