### PR TITLE
Recursive `.yaml` inheritance

### PR DESCRIPTION
**Pull request by matthewlchambers**
This PR implements a new optional entry in `source.yaml` files. If a `source.yaml` file contains the key `inherits_from`, the value associated with this key is interpreted as the name of another `.yaml` file in the same folder which should be read in and combined with the original `source.yaml` file to produce the `config` dictionary.

Merging the dictionaries is done such that if `parent.yaml` and `child.yaml` contain the same key, the value from `child.yaml` will be the one used in `config`. A warning is logged in this situation so the user will be aware.

Additionally, inheritance is allowed to be recursive: `parent.yaml` may have the entry` inherits_from: grandparent.yaml`, and so on.

This should be helpful for sources like EQUATES and NEI which would otherwise have a lot of duplicated information across `.yaml` files. Now, for example, all common information for EQUATES can be held in `EQUATES_Common.yaml`, with nonpoint source specific information in `EQUATES_Nonpoint.yaml`. In this case, `EQUATES_Nonpoint.yaml` contains the entry `inherits_from: EQUATES_Common`.

### CODE REVIEW

**Comment by bl-young** [comment]
@matthewlchambers I like this idea - I had just started updating the NEI `.yaml` files re: #148 and was thinking about ways to avoid having to repeat the data dictionaries in each. (I was leaning towards the opposite approach of combining them into a single `.yaml` but this works just as well and will likely be more flexible moving forward)

**Comment by catherinebirney** [comment]
I also like this idea - it will also make it more clear what the differences are between yamls when we have more than one method of generating an FBS

**Comment by bl-young** [comment]
> when we have more than one method of generating an FBS

I believe this currenlty only impacts FBA.

FBS yaml files are read [here](https://github.com/USEPA/flowsa/blob/develop/flowsa/flowbysector.py#L71-L83), but really that should probably use the existing function in common so could work for FBS as well.

**Comment by catherinebirney** [comment]
@bl-young Ah yes, got ahead of myself - yes, the FBS should be modified to utilize @matthewlchambers changes

**Comment by matthewlchambers** [comment]
> @bl-young Ah yes, got ahead of myself - yes, the FBS should be modified to utilize @matthewlchambers changes

See #157, which implements this modification for FBS.

**Pull request merged**
