### PR TITLE
add 'MetaSources' column to FBS

### PR DESCRIPTION
**Pull request by catherinebirney**
Changes:
1. Adds MetaSources to FBS output
2. Adds fxn harmonize_FBS_columns(), which ensures there aren't multiple rows of data for a SectorProducedBy/SectorConsumedBy combo where the only differences in rows are FIPS year/MetaSource/MeasureofSpread

### CODE REVIEW

**Comment by bl-young** [comment]
@catherinebirney so you successfully built CAP_HAP? did you try any others?

**Comment by catherinebirney** [comment]
@bl-young GRDREL_national_2017 runs. I get an error with TRI_DMR_national_2017:
FileNotFoundError: [Errno 2] No such file or directory: '...Python/Python37/lib/site-packages/stewi/data/DMR/2_digit_SIC.csv'

**Comment by bl-young** [comment]
Ok probably the same issue as yesterday. I will adjust this line to make sure the entire data file is included in the install:
https://github.com/USEPA/standardizedinventories/blob/master/setup.py#L34

**Comment by catherinebirney** [comment]
@bl-young There is a problem with the latest commit, I get an error message when using the command line to install stewi:
ValueError: path 'data/' cannot end with '/'

**Comment by bl-young** [comment]
ok sorry try now

**Comment by catherinebirney** [comment]
Thanks - fixed the issue. I can now run TRI_DMR

**Review by bl-young — APPROVED** [review]

**Comment by bl-young** [comment]
ok did some testing myself on the data that comes out of StEWI and looks good to me.

**Comment by bl-young** [comment]
actually, @catherinebirney, given what you did in harmonize_fbs_columns, it's now safe for me to assign the datasource name individually from stewicombo, correct, and they should get combined. Let me check on that.

**Comment by catherinebirney** [comment]
> actually, @catherinebirney, given what you did in harmonize_fbs_columns, it's now safe for me to assign the datasource name individually from stewicombo, correct, and they should get combined. Let me check on that.

Yes, the datasource names should get combined

**Comment by bl-young** [comment]
will data quality get aggregated and averaged correctly?

**Comment by catherinebirney** [comment]
Data quality scores are calculated with a weighted average through the aggregator fxn
https://github.com/USEPA/flowsa/blob/master/flowsa/flowbyfunctions.py#L180
which is run after harmonize_fbs_columns. I didn't do any data testing (which I should), but the scores should be averaged correctly. I'll add a jira task to test the results

**Comment by bl-young** [comment]
Perfect, yeah I just tested in the TRI/DMR data and the data quality was the same as before for all flows. I misunderstood your function.

I will add that this can manifest as some records with "TRI, DMR" and others with "DMR, TRI". I dont know if there is an easy solution to that.

**Comment by catherinebirney** [comment]
> I will add that this can manifest as some records with "TRI, DMR" and others with "DMR, TRI". I dont know if there is an easy solution to that.

Ah okay, good catch! I wonder if sorting the df by MetaSources prior to joining MetaSources names would fix that. I'll check.

**Comment by catherinebirney** [comment]
@bl-young sorting the df by metasources prior to concating the metasource strings appears to have fixed the issue - although only tested with TRI_DMR. If you're happy with the changes I'll go ahead and merge

**Review by bl-young — APPROVED** [review]

**Pull request merged**
