### PR TITLE
add new energy data - EIA SEDS, AEO, update MECS

### PR DESCRIPTION
**Pull request by catherinebirney**
@bl-young Are these tables good to be pulled in?

### CODE REVIEW

**Comment by bl-young** [comment]
I'll have to confirm I don't recall when I last ran them.

**Comment by bl-young** [comment]
I'd like to review the final FBA one more time but I think these are ready

**Comment by catherinebirney** [comment]
@bl-young your update to specify which table to pull in to allocate nat gas is what I would have proposed

**Comment by bl-young** [comment]
> @bl-young your update to specify which table to pull in to allocate nat gas is what I would have proposed

So it turns out that we can't filter by the description FBA field as it gets dropped during cleaning [here](https://github.com/USEPA/flowsa/blob/energy_data/flowsa/dataclean.py#L30-L31). We will need a different approach.

**Comment by catherinebirney** [comment]
@bl-young I addressed that issue in the waste branch to keep the description because I wanted to filter by the REI description - let me find that change and might be able to cherry pick that commit into the energy branch

**Comment by catherinebirney** [comment]
@bl-young I cherry picked the commit to retain the description in FBS methods but did not test in the energy branch. In the FBS yaml there is now an "allocation_selection_fields" (like Matthew set up in his branch) where you specify a column and a list of info to keep. See the [REI_waste_national_2012.yaml](https://github.com/USEPA/flowsa/blob/waste/flowsa/methods/flowbysectormethods/REI_waste_national_2012.yaml#L24)

**Review by bl-young — APPROVED** [review]

**Pull request merged**
