### PR TITLE
Generate metadata for FBA and FBS

### PR DESCRIPTION
**Pull request by catherinebirney**
- generate fba metadata
- generate fbs metadata by calling on previously generated fba meta
- ensure all FBAs (including those called on within a function) used to generated a FBS are accounted for in the metadata and the bibliography
- remove "date_generated" parameter from FBA method yaml, instead capture the date_generated in the meta
- update package version to 0.2 (dependencies on metadata justify a jump)

### CODE REVIEW

**Comment by bl-young** [comment]
@catherinebirney  ok for me to reivew (may not happen til Monday) or should I want for any last commits?

**Comment by catherinebirney** [comment]
@bl-young Yes, please review when you have the time. Although, I did not test for stewi...
I added v0.2 of the parquets and meta to the sharepoint folder (Data Commons is down)

**Comment by bl-young** [comment]
@catherinebirney made a few changes to facilitate pulling metadata from stewi, also needed to add some exceptions for FBS that are just from stewicombo see https://github.com/USEPA/flowsa/pull/89/commits/ad364bba3de7822b5583ccca19709c2c6cf7ed0d.

Note to do this I pulled in the stewi branch, which aligns with v0.9.8 of stewi which is the pending refac for esupy

**Review by bl-young — APPROVED** [review]

**Comment by catherinebirney** [comment]
Looks good, thanks! will merge the pull request.

**Pull request merged**
