### PR TITLE
Update BEA data with latest data

### PR DESCRIPTION
**Pull request by bl-young**
- Updates 2012 Make and Use tables to use latest BEA release in Fall of 2021 (see https://github.com/USEPA/useeior/pull/221)
- Updates industry gross output data from same release, and expands to include 2019 and 2020 data years
- deprecated `BEA_2012_Detail_Use_Industry_Transactions.csv` removed to avoid confusion

### CODE REVIEW

**Comment by bl-young** [comment]
cc @catherinebirney tagging you so you are aware

**Review by MoLi7 — APPROVED** [review]

**Comment by bl-young** [comment]
Due to the expected changes in FBS, wait until #231 is merged

**Comment by bl-young** [comment]
@MoLi7 I noticed that the new BEA data for Gross Output only has 404 sectors instead of 405, perhaps due to that Drugs and druggists' sector issue you recently fixed (after I pulled in the data). I'll propose that we wait until useeior has been released before we confirm those updates here and pull this in.

**Comment by MoLi7** [comment]
Yes, the issue Ben raised has been fixed in useeior v1.1.0.

**Pull request merged**
